%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  

imu_topic: "/mynteye/imu/data_raw"
image0_topic: "/mynteye/left/image_raw"
output_path: "/home/clarence/MYNT-EYE-original_ws_tmp"

#cam0_calib: "left_equ.yaml"
#cam0_calib: "left_pinhole.yaml"
cam0_calib: "left_mei.yaml"
#cam0_calib: "right_mei.yaml"
image_width: 752
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.0064662, -0.99994994, -0.00763565, 0.00533646,
           0.99997909, -0.00646566, -0.00009558, -0.04302922,
           0.0000462, -0.00763611, 0.99997084, 0.02303124,
           0, 0, 0, 1]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.8  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.8         # gravity magnitude

#acc_n: 0.0268014618074          # accelerometer measurement noise standard deviation. #0.599298904976
#gyr_n: 0.00888232829671         # gyroscope measurement noise standard deviation.     #0.198614898699
#acc_w: 0.00262960861593         # accelerometer bias random work noise standard deviation.  #0.02
#gyr_w: 0.000379565782927        # gyroscope bias random work noise standard deviation.     #4.0e-5
#g_norm: 9.81007                 # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 1      # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/clarence/MYNT-EYE-original_ws_tmp/src/pose_graph" # save and load path
save_image: 1                    # save image in pose graph for visualization prupose; you can close this function by setting 0 
pg_R_vio_buffer_length: 10       # for n3ctrl 
pg_t_vio_buffer_length: 5        # for n3ctrl

#_____________________________Optimization Settings______________________________
#_______switches_____|____vins___|_vins+uwb_(no_sift)_|_uwb_only_|_sift_|_other_|
#  uwb               |     0     |         1          |     1    |   1  |       |
#  ekf               |     0     |         1          |     1    |   1  |       |
#  uwb_optimize      |     0     |         1          |     1    |   1  |       |
#  vision_optimize   |     1     |         1          |     0    |   1  |  ...  |
#  imu_optimize      |     1     |         1          |     1    |   1  |       |
#  margin_optimize   |     1     |         1          |     1    |   1  |       |
#  test_feature      |     0     |         0          |     0    |   1  |       |

#uwb
uwb: 0                  # use uwb or not
ekf: 0                  # use uwb ekf or not
uwb_dis_cov: 0.0004     # uwb range covariance
rssi_threshold: -93.0   # uwb rssi threshold

#optimization modules 
uwb_optimize: 0      # use uwb for optimization
vision_optimize: 1   # use visual features for optimization
imu_optimize: 1      # use imu data for optimization
margin_optimize: 1   # use marginalization info for optimization

#test feature
test_feature: 1      # 0   use all features in BA
                     # 1   test features
test_feature_num: 30
